config/routes.rb
MusicStream::Application.routes.draw do
  get "welcome/index"

  controller :admin do
    get 'admin' => :index
    get '/admin/user/:id' => :user
    put '/admin/user/:id' => :update
    delete '/admin/user/:id' => :destroy_music
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :users do
    get 'signup' => :new
    post 'signup' => :create
    get 'music' => :show
    post 'music' => :upload
    delete 'music' => :destroy_music
    get 'edit' => :edit
    put 'edit' => :update
    delete '/users/:id' => :destroy
  end

  root :to => 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music Stream</title>
    <link rel="shortcut icon" href="<%= asset_path('favicon.ico') %>"/>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "bootstrap/bootstrap.css" %>
    <%= csrf_meta_tags %>
    <script>
      $(function() {
        $("#notice").delay(2000).hide(2000);
      });
    </script>
    <%= yield(:head) if content_for? :head %>
  </head>

  <body class="<%= controller.controller_name %>">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <%= link_to 'Music Stream', root_path, class: 'brand' %>
          <div class="navbar-text pull-right">
            <ul class="nav">
              <% if session[:user_id] %>
                <li><%= link_to(get_session_user.name, edit_path) %></li>
                <% if get_session_user.is_admin? %>
                  <li><%= link_to('Admin', admin_path) %></li>
                <% end %>
                <li><%= link_to('Logout', logout_path, method: :delete) %></li>
              <% else %>
                <li><%= link_to('Sign-up', signup_path) %></li>
                <li><%= link_to('Login', login_path) %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div id="notice_container">
      <% if flash.alert %>
        <p id="notice" class="alert alert-error"><%= flash.alert %></p>
      <% elsif notice %>
        <p id="notice" class="alert alert-success"><%= notice %></p>
      <% end %>
    </div>

    <%= yield %>

    <div class="navbar navbar-inverse navbar-fixed-bottom">
      <div class="navbar-inner">
        <div class="container-fluid">
          <div class="navbar-text pull-left">
            <ul class="nav">
              <li><a>Made by Joshua French</a></li>
            </ul>
          </div>
          <div class="navbar-text pull-right">
            <ul class="nav">
              <li><a href="https://github.com/JllyGrnGiant/music_stream/">https://github.com/JllyGrnGiant/music_stream/</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>